<div id='main-container'>
    <div class="row">
        <div class="col-lg-4">
            <div class="thumbnail">
                <img data-src='<?php echo $this->basePath() . '/img/avatar.jpg' ?>' alt="" src='<?php echo $this->basePath() . '/img/avatar.jpg' ?>' style='width: 100%'>
            </div>
            <div class='description-section panel'>
                <a href='https://github.com/dpetek'>
                    <img src='<?php echo $this->basePath() . "/img/social-icon/github-icon.png"; ?>' class='social-icon' />
                </a>
                <a href='http://www.linkedin.com/pub/denis-petek/29/a07/479/'>
                    <img src='<?php echo $this->basePath() . "/img/social-icon/linkedin-icon.png"; ?>' class='social-icon' />
                </a>
                <a href="javascript:void(0)" data-toggle="tooltip" title="dpetek1" rel='tooltip'>
                    <img src='<?php echo $this->basePath() . "/img/social-icon/skype-icon.png"; ?>' class='social-icon' />
                </a>
                <a href='https://www.facebook.com/denis.petek'>
                    <img src='<?php echo $this->basePath() . "/img/social-icon/facebook-icon.png"; ?>' class='social-icon' />
                </a>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">About</h3>
                </div>
                <p>
                    I'm 24 year old software engineer from Croatia. Currently working at <a href='//thebackplane.com'>The Backplane</a> in Palo Alto.
                </p>
                <p>
                    I have a <strong>Master degree in Computer Science</strong> from <a href='//fer.hr'>Faculty of Electrical Engineering and Computing in Zagreb</a>.
                </p>
            </div>

            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Skills</h3>
                </div>

                <a data-toggle="modal" href="#linuxSkill" class="">
                    <img src='<?php echo $this->basePath() . "/img/skills-icons/linux.png"; ?>' class='social-icon' />
                </a>
                <div class="modal fade" id="linuxSkill">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Linux</h4>
                            </div>
                            <div class="modal-body">
                                Active linux user. Bash scripting experience as well.
                            </div>
                        </div>
                    </div>
                </div>
                <br /> <br />

                <a data-toggle="modal" href="#cppSkill" class="">
                    <img src='<?php echo $this->basePath() . "/img/skills-icons/cpp.png"; ?>' class='social-icon' />
                </a>
                <div class="modal fade" id="cppSkill">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">C/C++</h4>
                            </div>
                            <div class="modal-body">
                                8 years of experience in C/C++ programming. Mostly used for problem solving and algorithm competitions.
                            </div>
                        </div>
                    </div>
                </div>


                <a data-toggle="modal" href="#phpSkill" class="">
                    <img src='<?php echo $this->basePath() . "/img/skills-icons/php.png"; ?>' class='social-icon' />
                </a>
                <div class="modal fade" id="phpSkill">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">PHP</h4>
                            </div>
                            <div class="modal-body">
                                PHP web developing experience.
                            </div>
                        </div>
                    </div>
                </div>

                <a data-toggle="modal" href="#javaSkill" class="">
                    <img src='<?php echo $this->basePath() . "/img/skills-icons/java.png"; ?>' class='social-icon' />
                </a>
                <div class="modal fade" id="javaSkill">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Java</h4>
                            </div>
                            <div class="modal-body">
                                PHP web developing experience.
                            </div>
                        </div>
                    </div>
                </div>

                <a data-toggle="modal" href="#pythonSkill" class="">
                    <img src='<?php echo $this->basePath() . "/img/skills-icons/python.png"; ?>' class='social-icon' />
                </a>
                <div class="modal fade" id="pythonSkill">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Java</h4>
                            </div>
                            <div class="modal-body">
                                PHP web developing experience.
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>