<div id='main-container'>
    <div class="hero-unit">
        <table style='width: 100%'>
            <tr>
                <td style='vertical-align: top;width: 50%'>

                    <div class="thumbnail" style='width: 300px'>
                        <img data-src='<?php echo $this->basePath() . '/img/avatar.jpg' ?>' alt="" style="width: 300px; height: 200px;" src='<?php echo $this->basePath() . '/img/avatar.jpg' ?>'>
                        <div class="caption">
                            <h3>Denis Petek</h3>
                            <p style='font-size: 12px'>
                                <blockquote style='font-size: 12px;border-color: #888;'>
                                    24 year old software enginner. Currently working at The Backplane, Inc in Palo Alto.
                                </blockquote>
                                <blockquote style='font-size: 12px;border-color: #888;'>
                                    <strong>Master degree in Computer Science</strong> | Faculty of Electrical Engineering and Computing in Zagreb
                                </blockquote>
                              </p>
                        </div>
                    </div>
                </td>
                <td style='vertical-align: top'>
                    <div class='description-section'>
                            <p class='img-polaroid'>
                                OS:
                            </p>

                        <img src='<?php echo $this->basePath() . "/img/social-icon/linux-icon.png"; ?>' class='social-icon' />
                        <img src='<?php echo $this->basePath() . "/img/social-icon/android-icon.png"; ?>' class='social-icon' />
                    </div>
                    <div class='description-section'>
                            <p class='img-polaroid'>
                                Social networks and other:
                            </p>
                        <a href='https://github.com/dpetek'>
                            <img src='<?php echo $this->basePath() . "/img/social-icon/github-icon.png"; ?>' class='social-icon' />
                        </a>
                        <a href="javascript:void(0)" data-toggle="tooltip" data-html='dpetek1' title="dpetek1">
                            <img src='<?php echo $this->basePath() . "/img/social-icon/skype-icon.png"; ?>' class='social-icon' />
                        </a>
                        <a href='https://www.facebook.com/denis.petek'>
                            <img src='<?php echo $this->basePath() . "/img/social-icon/facebook-icon.png"; ?>' class='social-icon' />
                        </a>
                        <img src='<?php echo $this->basePath() . "/img/social-icon/google-icon.png"; ?>' class='social-icon' />
                        <img src='<?php echo $this->basePath() . "/img/social-icon/twitter-icon.png"; ?>' class='social-icon' />
                    </div>
                </td>
            </tr>
        </table>

    </div>
</div>

