<div id='main-container'>
    <div class="hero-unit main-hero-unit">
            <div class="thumbnail" style='' id='personal-avatar'>
                <img data-src='<?php echo $this->basePath() . '/img/avatar.jpg' ?>' alt="" src='<?php echo $this->basePath() . '/img/avatar.jpg' ?>'>
                <div class="caption">
                    <h3>Denis Petek</h3>
                    <p style='font-size: 12px'>
                        <blockquote style='font-size: 12px;border-color: #888;'>
                            24 year old software engineer. Currently working at The Backplane, Inc in Palo Alto.
                        </blockquote>
                        <blockquote style='font-size: 12px;border-color: #888;'>
                            <strong>Master degree in Computer Science</strong> | Faculty of Electrical Engineering and Computing in Zagreb
                        </blockquote>
                      </p>
                </div>
                <div class='description-section'>
                    <a href='https://github.com/dpetek'>
                        <img src='<?php echo $this->basePath() . "/img/social-icon/github-icon.png"; ?>' class='social-icon' />
                    </a>
                    <a href='http://www.linkedin.com/pub/denis-petek/29/a07/479/'>
                        <img src='<?php echo $this->basePath() . "/img/social-icon/linkedin-icon.png"; ?>' class='social-icon' />
                    </a>
                    <a href="javascript:void(0)" data-toggle="tooltip" title="dpetek1" rel='tooltip'>
                        <img src='<?php echo $this->basePath() . "/img/social-icon/skype-icon.png"; ?>' class='social-icon' />
                    </a>
                    <a href='https://www.facebook.com/denis.petek'>
                        <img src='<?php echo $this->basePath() . "/img/social-icon/facebook-icon.png"; ?>' class='social-icon' />
                    </a>
                </div>
            </div>
        <div class='description-container'>

        </div>

    </div>
</div>

