<div class='jumbotron'>
    Hope you like puzzles as much as I do. Here you can solve some of them. I'll keep updating this page so you are never bored here. You are welcome.
</div>

<div class='panel'>
    Your progress:
    <div class="progress progress-striped">
        <div class="progress-bar progress-bar-danger" style="width: 4%"></div>
    </div>
</div>

<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description preview</th>
            <th>Num solved</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><a href='#'>Prime fibonacci</a></td>
            <td>Among first 20 fibonacci numbers, how many of them are prime? </td>
            <td>0/0</td>
        </tr>
    </tbody>
</table>